config/routes.rb
Rails.application.routes.draw do
  resources :create_users
  resources :posts

  root 'welcome#home'

  get 'signup' => 'users#new'
  
  post 'users', to: 'users#create'

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :posts 
    before_save { self.email = email.downcase }
validates :username, presence: true,

uniqueness: { case_sensitive: false },

length: { minimum: 3, maximum: 25 }

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :email, presence: true, length: { maximum: 105 },

uniqueness: { case_sensitive: false },

format: { with: VALID_EMAIL_REGEX }

has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/create_users_controller.rb
class CreateUsersController < ApplicationController
  before_action :set_create_user, only: [:show, :edit, :update, :destroy]

  # GET /create_users
  # GET /create_users.json
  def index
    @create_users = CreateUser.all
  end

  # GET /create_users/1
  # GET /create_users/1.json
  def show
  end

  # GET /create_users/new
  def new
    @create_user = CreateUser.new
  end

  # GET /create_users/1/edit
  def edit
  end

  # POST /create_users
  # POST /create_users.json
  def create
    @create_user = CreateUser.new(create_user_params)

    respond_to do |format|
      if @create_user.save
        format.html { redirect_to @create_user, notice: 'Create user was successfully created.' }
        format.json { render :show, status: :created, location: @create_user }
      else
        format.html { render :new }
        format.json { render json: @create_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_users/1
  # PATCH/PUT /create_users/1.json
  def update
    respond_to do |format|
      if @create_user.update(create_user_params)
        format.html { redirect_to @create_user, notice: 'Create user was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_user }
      else
        format.html { render :edit }
        format.json { render json: @create_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_users/1
  # DELETE /create_users/1.json
  def destroy
    @create_user.destroy
    respond_to do |format|
      format.html { redirect_to create_users_url, notice: 'Create user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_user
      @create_user = CreateUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_user_params
      params.require(:create_user).permit(:username, :email)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    debugger
    @post = Post.new(post_params)
    @post.user = User.first
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            flash[:success] = "Welcome to the ariel blog#{@user.username}"
            redirect_to posts_path
        else
            render 'new'
        end
        
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
        
    end
end

app/controllers/welcome_controller.rb
class WelcomeController <ApplicationController

 def home
 end

 def about
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_users_helper.rb
module CreateUsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/create_users/_form.html.erb
<%= form_for(@create_user) do |f| %>
  <% if @create_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@create_user.errors.count, "error") %> prohibited this create_user from being saved:</h2>

      <ul>
      <% @create_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/create_users/edit.html.erb
<h1>Editing Create User</h1>

<%= render 'form' %>

<%= link_to 'Show', @create_user %> |
<%= link_to 'Back', create_users_path %>

app/views/create_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Create Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @create_users.each do |create_user| %>
      <tr>
        <td><%= create_user.username %></td>
        <td><%= create_user.email %></td>
        <td><%= link_to 'Show', create_user %></td>
        <td><%= link_to 'Edit', edit_create_user_path(create_user) %></td>
        <td><%= link_to 'Destroy', create_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create user', new_create_user_path %>

app/views/create_users/new.html.erb
<h1>New Create User</h1>

<%= render 'form' %>

<%= link_to 'Back', create_users_path %>

app/views/create_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @create_user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @create_user.email %>
</p>

<%= link_to 'Edit', edit_create_user_path(@create_user) %> |
<%= link_to 'Back', create_users_path %>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy Ariel blog
        </small>
        <nav>
            <ul>
                <li> <%= link_to "About", "#" %></li>
                <li> <%= link_to "me", "#" %></li>
                <li> <%= link_to "you", "#" %></li>
            </ul>
        </nav>
    </footer>
    
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <!-- <a class="navbar-brand" id="logo" href="#">Ariel blog</a>-->
      <%= link_to "Ariel blog",root_path,class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li class="active"><%= link_to "Post",posts_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "post", posts_path %></li>
            <li><%= link_to "create", new_post_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar'%>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer'%>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/_form.html.erb
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  
  <div class='row'>
    <div class='col-md-12'>
      <%= form_for(@post) do |f| %>
      <div class='form-horizontal'>
    
      <div class='form-group'>
        <div class='col-sm-2 control-label'>
          <%= f.label :title %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_field :title, class: "control-control",placeholder: "Title" %>
        </div>
      </div>
        
      <div class='form-group'>
        <div class='col-sm-2 control-label'>
          <%= f.label :content%>
        </div>
        <div class='col-sm-10'>
          <%= f.text_area :content, rows:10, class: "control-control",placeholder: "Content" %>
        </div>
      </div>
        
        <div class='form-group'>
          <div class='col-sm-offset-2 col-sm-10'>
          <%= f.submit class:'btn btn-primary btn-lg' %>
        </div>
        </div>
        </div>
      <% end %>
    </div>
    
  </div>

app/views/posts/edit.html.erb
<h1 align="center">Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>




    <% @posts.each do |post| %>
    
    <div class ="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%=link_to post.title, post %>
          </div>
          <div class="article-body">
            <%= truncate(post.content, length: 100) %>
            <div class="article-meta-details">
            <small>Created by: <%= post.user.username if post.user %></small>
            </div>
          </div>
     
       <div class="article-actions">
        <%= link_to 'Edit', edit_post_path(post),class:"btn btn-xs btn-primary" %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-xs btn-danger" %>
        </div>
      </div>
      </div>      
    </div>
    <% end %>


<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1 align="center">New Post</h1>

<%= render 'form' %>
<div class="col-xs-4 col-xs-offset-4">
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1 align=center>Sign up</h1>
 
 
  <div class='row'>
    <div class='col-md-12'>
      <%= form_for(@user) do |f| %>
      <div class='form-horizontal'>
    
      <div class='form-group'>
        <div class='col-sm-2 control-label'>
          <%= f.label :username %>
        </div>
        <div class='col-sm-10'>
          <%= f.text_field :username, class: "control-control",placeholder: "username" %>
        </div>
      </div>
        
      <div class='form-group'>
        <div class='col-sm-2 control-label'>
          <%= f.label :email%>
        </div>
        <div class='col-sm-10'>
          <%= f.email_field :email, class: "control-control",placeholder: "email" %>
        </div>
      </div>
      
      <div class='form-group'>
        <div class='col-sm-2 control-label'>
          <%= f.label :password%>
        </div>
        <div class='col-sm-10'>
          <%= f.password_field :password, class: "control-control",placeholder: "password" %>
        </div>
      </div>
        
        <div class='form-group'>
          <div class='col-sm-offset-2 col-sm-10'>
          <%= f.submit "Sign up", class:'btn btn-primary btn-lg' %>
        </div>
        </div>
        </div>
      <% end %>
    </div>
    
  </div>

app/views/welcome/home.html.erb
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>welcome to Ariels blog</p>
  <p>
    <a class="btn btn-primary btn-danger btn-xlg" href="#" role="button">Learn more</a>
    
    </p>
</div>